name: Server - Feature
run-name: Server - Feature

on:
  pull_request:
    branches:
      - main

jobs:

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="

  main_branch:
    name: Feature Branch Build
    runs-on: ubuntu-latest
    needs: debug

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Build
        run: mvn package
