name: Server - Release
run-name: Server - Release

on:
  push:
    branches:
      - main

jobs:

  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "============="
          echo "=== Debug ==="
          echo "============="

  main_branch:
    name: Main Branch Build
    runs-on: ubuntu-latest
    needs: debug

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Build
        run: mvn package

  semantic_release:
    name: Semantic Release
    uses: ./.github/workflows/versioning.yml
    secrets: inherit

